services:
  svelte-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=production
